const { envelop, useSchema } = require("@envelop/core");
const { useParserCache } = require("@envelop/parser-cache");
const { useValidationCache } = require("@envelop/validation-cache");
const { makeExecutableSchema } = require("@graphql-tools/schema");
const resolvers = require("./resolver");

const schema = {
  typeDefs: /* GraphQL */ `
    type Query {
      hello: AutogeneratedMainType!
    }
    type DevDependencies {
      nodemon: String
    }

    type Dependencies {
      express: String
      graphql: String
    }

    type Scripts {
      start: String
    }

    type PackageJson {
      name: String
      version: String
      description: String
      main: String
      keywords: [String]
      devDependencies: DevDependencies
      dependencies: Dependencies
      scripts: Scripts
    }

    type AutogeneratedMainType {
      packageJSON: PackageJson
    }
  `,
  resolvers,
};

const executableSchema = makeExecutableSchema(schema);

module.exports = {
  ...schema,
  getEnveloped: envelop({
    plugins: [
      useSchema(executableSchema),
      useParserCache(),
      useValidationCache(),
    ],
  }),
};
